# Time Complexity: O(1)
# Space Complexity: O(1)
print("     /~\\")
print("    ( oo|")
print("    _\\=/_")
print("   /  _  \\")
print("  //|/.\|\\\\")
print(" ||  \\ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")
